# Environment configuration for Selenium Pytest Framework

# Set the environment: dev, qa, staging, prod
environment: dev

# Selenium Grid configuration
grid_url: http://localhost:4444/wd/hub


# URLs for different environments
urls:
  dev: "http://demostore.supersqa.com/"
  qa: "http://demostore.supersqa.com/"
  staging: "http://demostore.supersqa.com/"
  prod: "http://demostore.supersqa.com/"

# Database connection strings for different environments
db_connection:
  dev: "postgresql://user:password@localhost:5432/devdb"
  qa: "postgresql://user:password@localhost:5432/qadb"
  staging: "postgresql://user:password@localhost:5432/stagingdb"
  prod: "postgresql://user:password@localhost:5432/proddb"

# Browser settings
browser: chrome
headless: false